### ISSUE TITLE
Watched/Unwatched filter issue in My tv shows

### ISSUE THREAD

**Issue by PacQ** [the13clowns/_zips#3]
Hi. When traversing  backward in "My TV shows > Collection > series > season", for example - from inside season 5 of some series back to list of seasons there will suddenly be showing all watched content (seasons 1,2,3,4&5) instead of just Unwatched content (season 5) that is set to be shown. Then when going back to series and forward to list of seasons again the content will refresh and finally just Unwatched content will be displayed (season 5). Toggling filter doesn't change the displayed content. The same issue is happening with "My movies" category. 
I'm using Nvidia shield TV, Kodi 8.2, 13clowns 5.0.10a (but the issue persists from earlier versions) and I use Takt.

**Comment by the13clowns** [comment]
Fixed, please update.

**Comment by PacQ** [comment]
Hi. I now have version 5.0.12, but the bug still persists.  Kind regards.
